name: Julia M. Van Cleve
gems: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"
permalink: "/blog/:title"
highlighter: "pygments"
navigation:
- text: Home
  url: /
- text: Blog
  url: /blog/
- text: Portfolio
  url: /portfolio/
- text: Archive
  url: /archive/
